### PR TITLE
remove the cache on logout which fix the chat initialization on login

### LINKED ISSUE #44: When logout then login, the app is wrongly initialised
When you logout and then login in the same browser, the app is initialised with the data from the account that has been logged out.

### PR DESCRIPTION
**Pull request by MatLBS**
Fixes #44 

- Clear cache on logout
- Chats in the sidebar are initialized correctly when on another user connection

### CODE REVIEW

File: apps/frontend/src/main.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const router = createRouter({
 });
 
 /** Query client for state management */
-const queryClient = new QueryClient({
+export const queryClient = new QueryClient({
```
Comment (Standlc) [inline apps/frontend/src/main.tsx]: i'm not again exporting it, but the defacto in the codebase is to get a hold of the `queryClient` through `useQueryClient`. Either you revert the export and use the hook where you need it, or remove the hook everywhere it's used and import the `queryClient` directly instead.

Comment (MatLBS) [reply apps/frontend/src/main.tsx]: I removed the export and use 'useQueryClient'
